apiVersion: apps/v1
kind: Deployment
metadata:
  name: penpot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penpot-frontend
  template:
    metadata:
      labels:
        app: penpot-frontend
    spec:
      containers:
        - name: frontend
          image: penpotapp/frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: penpot-assets
              mountPath: /opt/data/assets
          env:
            - name: PENPOT_FLAGS
              value: "enable-registration enable-login-with-password"
      volumes:
        - name: penpot-assets
          persistentVolumeClaim:
            claimName: penpot-assets-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: penpot-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
  selector:
    app: penpot-frontend

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: penpot-assets-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/penpot-assets

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-assets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
