apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: penpot-assets
  name: penpot-assets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
