apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: penpot-postgres-v15
  name: penpot-postgres-v15
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
