apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: penpot-exporter
  name: penpot-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: penpot-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: penpot-exporter
    spec:
      containers:
        - env:
            - name: PENPOT_PUBLIC_URI
              value: http://penpot-frontend
            - name: PENPOT_REDIS_URI
              value: redis://penpot-redis/0
          image: penpotapp/exporter:latest
          name: penpot-exporter
      restartPolicy: Always
