apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
    traefik.enable: "true"
  labels:
    io.kompose.service: penpot-frontend
  name: penpot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: penpot-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
        traefik.enable: "true"
      labels:
        io.kompose.service: penpot-frontend
    spec:
      containers:
        - env:
            - name: PENPOT_FLAGS
              value: enable-registration enable-login-with-password
          image: penpotapp/frontend:latest
          name: penpot-frontend
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/data/assets
              name: penpot-assets
      restartPolicy: Always
      volumes:
        - name: penpot-assets
          persistentVolumeClaim:
            claimName: penpot-assets
