apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: penpot-postgres
  name: penpot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: penpot-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: penpot-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: penpot
            - name: POSTGRES_INITDB_ARGS
              value: --data-checksums
            - name: POSTGRES_PASSWORD
              value: penpot
            - name: POSTGRES_USER
              value: penpot
          image: postgres:15
          name: penpot-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: penpot-postgres-v15
      restartPolicy: Always
      volumes:
        - name: penpot-postgres-v15
          persistentVolumeClaim:
            claimName: penpot-postgres-v15
