apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: penpot
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: penpot
  source:
    repoURL: https://github.com/yuweirex/k8s.git
    targetRevision: HEAD
    path: apps/app2/dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
